#ifndef KEY_H
#define KEY_H

#include <glad/glad.h>
#include <GLFW/glfw3.h>

enum Key {
	ESC = GLFW_KEY_ESCAPE,
	SPACE = GLFW_KEY_SPACE,
	ENTER = GLFW_KEY_ENTER,
	BACKSPACE = GLFW_KEY_BACKSPACE,
	LSHIFT = GLFW_KEY_LEFT_SHIFT,
	RSHIFT = GLFW_KEY_RIGHT_SHIFT,
	W = GLFW_KEY_W,
	A = GLFW_KEY_A,
	S = GLFW_KEY_S,
	D = GLFW_KEY_D,
	KEY1 = GLFW_KEY_1,
	KEY2 = GLFW_KEY_2,
	KEY3 = GLFW_KEY_3,
	KEY4 = GLFW_KEY_4,
	KEY5 = GLFW_KEY_5,
	KEY6 = GLFW_KEY_6
};

#endif